"""fases 2-5 schema

Revision ID: 0bbedda6eb75
Revises: 
Create Date: 2026-06-19 10:29:09.619073

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbedda6eb75'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('tier', sa.Enum('simple', 'medium', 'premium', name='category_tier'), server_default='medium', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_active'), 'categories', ['active'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'professional', 'admin', name='user_role'), server_default='customer', nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'blocked', name='user_status'), server_default='active', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_phone_active', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_city'), 'customer_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_customer_profiles_state'), 'customer_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('leads',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lead_type', sa.Enum('one_time', 'temporary', 'permanent', name='lead_type'), nullable=False),
    sa.Column('urgency', sa.Enum('immediate', 'today', 'this_week', 'flexible', name='lead_urgency'), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('open', 'purchased', 'closed', 'cancelled', name='lead_status'), server_default='open', nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_category_id'), 'leads', ['category_id'], unique=False)
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_state'), 'leads', ['state'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_category_city_state', 'leads', ['status', 'category_id', 'city', 'state'], unique=False)
    op.create_table('professional_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('service_radius_km', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('premium', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('availability_status', sa.Enum('available', 'busy', 'unavailable', name='availability_status'), server_default='available', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_profiles_availability_status'), 'professional_profiles', ['availability_status'], unique=False)
    op.create_index(op.f('ix_professional_profiles_city'), 'professional_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_professional_profiles_state'), 'professional_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_professional_profiles_user_id'), 'professional_profiles', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_credit_wallets_balance_non_negative'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_wallets_professional_id'), 'credit_wallets', ['professional_id'], unique=True)
    op.create_table('lead_purchases',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_lead_purchases_professional_id'), 'lead_purchases', ['professional_id'], unique=False)
    op.create_index('ix_lead_purchases_professional_purchased', 'lead_purchases', ['professional_id', 'purchased_at'], unique=False)
    op.create_table('professional_categories',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'category_id', name='uq_professional_categories_pair')
    )
    op.create_index(op.f('ix_professional_categories_category_id'), 'professional_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_professional_categories_professional_id'), 'professional_categories', ['professional_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('purchase', 'bonus', 'refund', 'spend', 'adjustment', name='credit_transaction_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['credit_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_credit_transactions_wallet_created', 'credit_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_wallet_id'), 'credit_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_transactions_wallet_id'), table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_wallet_created', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_professional_categories_professional_id'), table_name='professional_categories')
    op.drop_index(op.f('ix_professional_categories_category_id'), table_name='professional_categories')
    op.drop_table('professional_categories')
    op.drop_index('ix_lead_purchases_professional_purchased', table_name='lead_purchases')
    op.drop_index(op.f('ix_lead_purchases_professional_id'), table_name='lead_purchases')
    op.drop_table('lead_purchases')
    op.drop_index(op.f('ix_credit_wallets_professional_id'), table_name='credit_wallets')
    op.drop_table('credit_wallets')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_professional_profiles_user_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_state'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_city'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_availability_status'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index('ix_leads_status_category_city_state', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_state'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_index(op.f('ix_leads_category_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_state'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_city'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index('uq_users_phone_active', table_name='users', postgresql_where=sa.text('phone IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
