"""fase 6 pagamentos

Revision ID: 13df944a4c96
Revises: 0bbedda6eb75
Create Date: 2026-06-19 11:07:17.098371

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13df944a4c96'
down_revision: str | None = '0bbedda6eb75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'BRL'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_credit_packages_credits_positive'),
    sa.CheckConstraint('price_cents >= 0', name='ck_credit_packages_price_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_credit_packages_active'), 'credit_packages', ['active'], unique=False)
    op.create_table('payment_orders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='BRL', nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'cancelled', name='payment_order_status'), server_default='pending', nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=True),
    sa.Column('pix_code', sa.Text(), nullable=True),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.String(length=255), nullable=True),
    sa.Column('credit_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_payment_orders_amount_non_negative'),
    sa.ForeignKeyConstraint(['package_id'], ['credit_packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_payment_orders_external_reference'), 'payment_orders', ['external_reference'], unique=True)
    op.create_index(op.f('ix_payment_orders_package_id'), 'payment_orders', ['package_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index('ix_payment_orders_user_created', 'payment_orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index('ix_payment_orders_user_created', table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_package_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_external_reference'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_credit_packages_active'), table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
